apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-BPUCJK
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: https
  useCommonServices: true
  version: 11.0.0.10-r1
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:87cd94979c040740b5c68931756498e43b5df9d5
        imagePullPolicy: Always
  configurations:
    - ibm-rest-dbparms.txt
    - ibm-rest-serverconf.yaml
    - ibm-rest-policy
    - ibm-ace-server.jks
    - ibm-ca.jks
