resources:
  - configuration/ibm_rest_serverconf_yaml.yaml
  - pipelines/ibm-test-pipeline-for-dev.yaml
  - tasks/0-setup.yaml
  - tasks/11-update-image.yaml
  - tasks/12-argo-tests.yaml
  - tasks/13-extract.yaml
  - configuration/ibm_rest_policy.yaml
